// Generated from assets/sprites — grey cat persona.

export const FRAME_WIDTH = 128;
export const FRAME_HEIGHT = 128;

export const ANIMATIONS = {
  dragged_front: ["dragged_front_0.png", "dragged_front_1.png", "dragged_front_2.png", "dragged_front_3.png", "dragged_front_4.png"],
  dragged_left: ["dragged_left_0.png", "dragged_left_1.png", "dragged_left_2.png", "dragged_left_3.png", "dragged_left_4.png", "dragged_left_5.png"],
  dragged_right: ["dragged_right_0.png", "dragged_right_1.png", "dragged_right_2.png", "dragged_right_3.png", "dragged_right_4.png"],
  happy_front: ["happy_front_0.png", "happy_front_1.png", "happy_front_2.png", "happy_front_3.png", "happy_front_4.png", "happy_front_5.png"],
  happy_left: ["happy_left_0.png", "happy_left_1.png", "happy_left_2.png", "happy_left_3.png", "happy_left_4.png", "happy_left_5.png"],
  happy_right: ["happy_right_0.png", "happy_right_1.png", "happy_right_2.png", "happy_right_3.png", "happy_right_4.png", "happy_right_5.png"],
  idle_front: ["idle_front_0.png", "idle_front_1.png", "idle_front_2.png", "idle_front_3.png", "idle_front_4.png"],
  idle_left: ["idle_left_0.png", "idle_left_1.png", "idle_left_2.png", "idle_left_3.png", "idle_left_4.png"],
  idle_right: ["idle_right_0.png", "idle_right_1.png", "idle_right_2.png", "idle_right_3.png", "idle_right_4.png"],
  jump_down_front: ["jump_down_front_0.png", "jump_down_front_1.png", "jump_down_front_2.png", "jump_down_front_3.png", "jump_down_front_4.png", "jump_down_front_5.png"],
  jump_down_left: ["jump_down_left_0.png", "jump_down_left_1.png", "jump_down_left_2.png", "jump_down_left_3.png", "jump_down_left_4.png", "jump_down_left_5.png"],
  jump_down_right: ["jump_down_right_0.png", "jump_down_right_1.png", "jump_down_right_2.png", "jump_down_right_3.png", "jump_down_right_4.png", "jump_down_right_5.png"],
  jump_up_front: ["jump_up_front_0.png", "jump_up_front_1.png", "jump_up_front_2.png", "jump_up_front_3.png", "jump_up_front_4.png", "jump_up_front_5.png"],
  jump_up_left: ["jump_up_left_0.png", "jump_up_left_1.png", "jump_up_left_2.png", "jump_up_left_3.png", "jump_up_left_4.png", "jump_up_left_5.png"],
  jump_up_right: ["jump_up_right_0.png", "jump_up_right_1.png", "jump_up_right_2.png", "jump_up_right_3.png", "jump_up_right_4.png", "jump_up_right_5.png"],
  overheated_front: ["overheated_front_0.png", "overheated_front_1.png", "overheated_front_2.png", "overheated_front_3.png", "overheated_front_4.png", "overheated_front_5.png"],
  overheated_left: ["overheated_left_0.png", "overheated_left_1.png", "overheated_left_2.png", "overheated_left_3.png", "overheated_left_4.png", "overheated_left_5.png"],
  overheated_right: ["overheated_right_0.png", "overheated_right_1.png", "overheated_right_2.png", "overheated_right_3.png", "overheated_right_4.png", "overheated_right_5.png"],
  run_front: ["run_front_0.png", "run_front_1.png", "run_front_2.png", "run_front_3.png", "run_front_4.png", "run_front_5.png", "run_front_6.png", "run_front_7.png"],
  run_left: ["run_left_0.png", "run_left_1.png", "run_left_2.png", "run_left_3.png", "run_left_4.png", "run_left_5.png", "run_left_6.png", "run_left_7.png"],
  run_right: ["run_right_0.png", "run_right_1.png", "run_right_2.png", "run_right_3.png", "run_right_4.png", "run_right_5.png", "run_right_6.png", "run_right_7.png"],
  sit_front: ["sit_front_0.png", "sit_front_1.png", "sit_front_2.png", "sit_front_3.png", "sit_front_4.png", "sit_front_5.png"],
  sit_left: ["sit_left_0.png", "sit_left_1.png", "sit_left_2.png", "sit_left_3.png", "sit_left_4.png", "sit_left_5.png"],
  sit_right: ["sit_right_0.png", "sit_right_1.png", "sit_right_2.png", "sit_right_3.png", "sit_right_4.png", "sit_right_5.png"],
  sleep_front: ["sleep_front_0.png", "sleep_front_1.png", "sleep_front_2.png", "sleep_front_3.png", "sleep_front_4.png", "sleep_front_5.png"],
  sleep_left: ["sleep_left_0.png", "sleep_left_1.png", "sleep_left_2.png", "sleep_left_3.png", "sleep_left_4.png", "sleep_left_5.png"],
  sleep_right: ["sleep_right_0.png", "sleep_right_1.png", "sleep_right_2.png", "sleep_right_3.png", "sleep_right_4.png", "sleep_right_5.png"],
  typing_aggressive_front: ["typing_aggressive_front_0.png", "typing_aggressive_front_1.png", "typing_aggressive_front_2.png", "typing_aggressive_front_3.png", "typing_aggressive_front_4.png", "typing_aggressive_front_5.png"],
  typing_aggressive_left: ["typing_aggressive_left_0.png", "typing_aggressive_left_1.png", "typing_aggressive_left_2.png", "typing_aggressive_left_3.png", "typing_aggressive_left_4.png", "typing_aggressive_left_5.png"],
  typing_aggressive_right: ["typing_aggressive_right_0.png", "typing_aggressive_right_1.png", "typing_aggressive_right_2.png", "typing_aggressive_right_3.png", "typing_aggressive_right_4.png", "typing_aggressive_right_5.png"],
  typing_calm_front: ["typing_calm_front_0.png", "typing_calm_front_1.png", "typing_calm_front_2.png", "typing_calm_front_3.png", "typing_calm_front_4.png", "typing_calm_front_5.png"],
  typing_calm_left: ["typing_calm_left_0.png", "typing_calm_left_1.png", "typing_calm_left_2.png", "typing_calm_left_3.png", "typing_calm_left_4.png", "typing_calm_left_5.png"],
  typing_calm_right: ["typing_calm_right_0.png", "typing_calm_right_1.png", "typing_calm_right_2.png", "typing_calm_right_3.png", "typing_calm_right_4.png", "typing_calm_right_5.png"],
  typing_exhausted_front: ["typing_exhausted_front_0.png", "typing_exhausted_front_1.png", "typing_exhausted_front_2.png", "typing_exhausted_front_3.png", "typing_exhausted_front_4.png", "typing_exhausted_front_5.png"],
  typing_exhausted_left: ["typing_exhausted_left_0.png", "typing_exhausted_left_1.png", "typing_exhausted_left_2.png", "typing_exhausted_left_3.png", "typing_exhausted_left_4.png", "typing_exhausted_left_5.png"],
  typing_exhausted_right: ["typing_exhausted_right_0.png", "typing_exhausted_right_1.png", "typing_exhausted_right_2.png", "typing_exhausted_right_3.png", "typing_exhausted_right_4.png", "typing_exhausted_right_5.png"],
  walk_front: ["walk_front_0.png", "walk_front_1.png", "walk_front_2.png", "walk_front_3.png", "walk_front_4.png", "walk_front_5.png", "walk_front_6.png", "walk_front_7.png"],
  walk_left: ["walk_left_0.png", "walk_left_1.png", "walk_left_2.png", "walk_left_3.png", "walk_left_4.png", "walk_left_5.png", "walk_left_6.png", "walk_left_7.png"],
  walk_right: ["walk_right_0.png", "walk_right_1.png", "walk_right_2.png", "walk_right_3.png", "walk_right_4.png", "walk_right_5.png", "walk_right_6.png", "walk_right_7.png"],
  working_front: ["working_front_0.png", "working_front_1.png", "working_front_2.png", "working_front_3.png", "working_front_4.png", "working_front_5.png"],
  working_left: ["working_left_0.png", "working_left_1.png", "working_left_2.png", "working_left_3.png", "working_left_4.png", "working_left_5.png"],
  working_right: ["working_right_0.png", "working_right_1.png", "working_right_2.png", "working_right_3.png", "working_right_4.png", "working_right_5.png"],
} as const;

export type AnimationName = keyof typeof ANIMATIONS;
